In [ ]:
!pip install -U transformers accelerate bitsandbytes sentencepiece

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Collecting transformers
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cu126)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Downloading transformers-4.57.6-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 90.1 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.1-py3-none-manylinux_2_24_x86_64.whl (59.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 10.5 MB/s eta 0:00:00
Installing collected packages: transformers, bitsandbytes
  Attempting uninstall: transformers
    Found existing installation: transformers 4.57.3
    Uninstalling transformers-4.57.3:
      Successfully uninstalled transformers-4.57.3
Successfully installed bitsandbytes-0.49.1 transformers-4.57.6

In [ ]:
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning, module='jupyter_client')

import pandas as pd
import json
import re
from typing import Annotated, TypedDict, Union, List
import operator

from sklearn.metrics import accuracy_score
from tqdm import tqdm
import random

import time
import subprocess

RANDOM_SEED = 42

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    dtype=torch.float16,
    device_map="auto",
    load_in_8bit=True
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/3.56G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

In [ ]:
data_path = '/content/drive/MyDrive/DLS_II_(NLP)/20_project_llm_agent_ya_search/data_final_for_dls_new.jsonl'
data_df = pd.read_json(data_path, lines=True)
train_df = data_df[570:]
eval_df = data_df[:570]
eval_df = eval_df[eval_df["relevance"] != 0.1]

## Prep data + baseline

In [ ]:
def prep_df(df):
    initial_len = len(df)

    # Удаляем дубликаты
    df = df.drop_duplicates(subset=['Text', 'name', 'address'])

    ambiguous_count = len(df[~df['relevance'].isin([0.0, 1.0])])
    df = df[df['relevance'].isin([0.0, 1.0])]
    if ambiguous_count > 0:
        print(f"Удалено {ambiguous_count} строк с нечеткой релевантностью (например, 0.1)")

    if len(df) < initial_len:
        print(f"Всего удалено (дубликаты + спорные): {initial_len - len(df)}")

    # Удаляем старый столбец relevance, если он существует
    if 'relevance' in df.columns:
        df = df.drop(columns=['relevance'])
        print("Удален старый столбец 'relevance'")

    # Переименовываем relevance_new в relevance, если он существует
    if 'relevance_new' in df.columns:
        df = df.rename(columns={'relevance_new': 'relevance'})
        print("Столбец 'relevance_new' переименован в 'relevance'")

    return df

In [ ]:
train_df = prep_df(train_df)

Удалено 4633 строк с нечеткой релевантностью (например, 0.1)
Всего удалено (дубликаты + спорные): 4638
Удален старый столбец 'relevance'
Столбец 'relevance_new' переименован в 'relevance'

In [ ]:
def parse_relevant(content: str) -> int:
    if not content:
        return 0

    # 1. Убираем code blocks ```json ... ```
    content = re.sub(r"```.*?```", "", content, flags=re.DOTALL)

    # 2. Ищем ВСЕ JSON-объекты
    matches = re.findall(r"\{[^{}]*\}", content)

    if not matches:
        return 0

    # 3. Берём ПОСЛЕДНИЙ JSON (модель могла привести пример раньше)
    for candidate in reversed(matches):
        try:
            obj = json.loads(candidate)
            if "relevant" in obj:
                val = obj["relevant"]
                if str(val).strip() == "1":
                    return 1
                if str(val).strip() == "0":
                    return 0
        except Exception:
            continue

    return 0

In [ ]:
def create_hard_golden_set(train_df, llm_predictor, search_size=5, target_size=2):

    subset = train_df.sample(n=min(len(train_df), search_size), random_state=RANDOM_SEED)

    hard_examples = []
    correct_count = 0

    for idx, row in tqdm(subset.iterrows(), total=len(subset)):
        if len(hard_examples) >= target_size:
            break

        pred = llm_predictor(row)
        truth = row['relevance']

        if float(pred) != float(truth):
            row_copy = row.copy()
            row_copy['baseline_pred'] = pred
            hard_examples.append(row_copy)
        else:
            correct_count += 1

    hard_df = pd.DataFrame(hard_examples)

    if not hard_df.empty:
        print(f"Готово. Найдено {len(hard_df)} сложных примеров.")
        print(f"Точность бейзлайна на этом куске: {correct_count / (correct_count + len(hard_examples)):.2f}")
    else:
        print("Не найдено ошибок! Попробуй увеличить search_size.")

    return hard_df

In [ ]:
def my_llm_call(row):
    prompt = f"""
Ты — бинарный классификатор.
Задача: Определи, соответствует ли организация запросу пользователя.

Верни ответ СТРОГО в виде одной строки JSON.
Никакого текста, никаких пояснений, никаких code block.

Формат ответа:
{{"relevant": 0}} или {{"relevant": 1}}

Запрос пользователя: "{row['Text']}"
Название организации: "{row['name']}"
Адрес: "{row['address']}"
Категория: "{row['normalized_main_rubric_name_ru']}"

Инструкция:
1. Проанализируй, релевантна ли организация запросу.
2. Если ДА, ответь {{"relevant": 1}}.
3. Если НЕТ, ответь {{"relevant": 0}}.
4. Не пиши никаких объяснений.
"""

    try:
        inputs = tokenizer(
            prompt,
            return_tensors="pt"
        ).to(model.device)

        with torch.no_grad():
            output = model.generate(
                **inputs,
                max_new_tokens=10,
                temperature=0.0,
                do_sample=False
            )

        generated_tokens = output[0][inputs["input_ids"].shape[-1]:]

        content = tokenizer.decode(
            generated_tokens,
            skip_special_tokens=True
        ).strip()

        pred = parse_relevant(content)

        return pred

    except Exception as e:
        print(f"LLM Error: {e}")
        return 0.0

In [ ]:
golden_set = create_hard_golden_set(train_df,
                                      llm_predictor=my_llm_call,
                                      search_size=50,
                                      target_size=20)

  0%|          | 0/50 [00:00<?, ?it/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
 68%|██████▊   | 34/50 [01:22<00:38,  2.42s/it]

Готово. Найдено 20 сложных примеров.
Точность бейзлайна на этом куске: 0.41

In [ ]:
correct = 0
total = 0
N = 50
subset = train_df.sample(
    n=min(len(train_df), N),
    random_state=RANDOM_SEED
)

for idx, row in tqdm(subset.iterrows(), total=len(subset)):

    prompt = f"""
Ты — бинарный классификатор.
Задача: Определи, соответствует ли организация запросу пользователя.

Верни ответ СТРОГО в виде одной строки JSON.
Никакого текста, никаких пояснений, никаких code block.

Формат ответа:
{{"relevant": 0}} или {{"relevant": 1}}

Запрос пользователя: "{row['Text']}"
Название организации: "{row['name']}"
Адрес: "{row['address']}"
Категория: "{row['normalized_main_rubric_name_ru']}"

Инструкция:
1. Проанализируй, релевантна ли организация запросу.
2. Если ДА, ответь {{"relevant": 1}}.
3. Если НЕТ, ответь {{"relevant": 0}}.
4. Не пиши никаких объяснений.
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=10,
            temperature=0.0,
            do_sample=False
        )
    generated_tokens = output[0][inputs["input_ids"].shape[-1]:]

    content = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    pred = parse_relevant(content)

    gt = int(row["relevance"])

    is_correct = pred == gt
    correct += int(is_correct)
    total += 1

    print(f"\n====== # {idx} ======")
    print(f"Text: {row['Text']}")
    print(f"Название организации: {row['name']}")
    print(f"GT:   {gt}")
    print(f"content: {content}")
    print(f"PRED: {pred}")
    print("РЕЗУЛЬТАТ:", "ВЕРНО" if is_correct else "НЕВЕРНО")
    print("-" * 40)

  2%|▏         | 1/50 [00:02<01:44,  2.14s/it]

====== # 19505 ======
Text: недорогие кафе геленджика
Название организации: Весёлая Кума; Vesolaya kuma; Весёлая кума; Ресторан Весёлая Кума
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

  4%|▍         | 2/50 [00:04<01:36,  2.01s/it]

====== # 12621 ======
Text: билет надо казахстан москва
Название организации: Трансмост-тур; Transmost-tour; Transmost-tur
GT:   1
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

  6%|▌         | 3/50 [00:05<01:28,  1.87s/it]

====== # 31518 ======
Text: расписание ортодонта города фрязино
Название организации: Магнит Косметик; Magnit Kosmetik
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

  8%|▊         | 4/50 [00:07<01:22,  1.80s/it]

====== # 2536 ======
Text: слесарный разметочный инструмент
Название организации: Milwaukee
GT:   1
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 10%|█         | 5/50 [00:09<01:20,  1.79s/it]

====== # 11967 ======
Text: главный жд вокзал
Название организации: Киевский вокзал; Kiyevsky Rail Terminal; Кіеўскі вакзал; Kiewer Bahnhof; Gare de Kiev; Kiev Garı; Київський вокзал; Kievsky Rail Terminal; Брянский вокзал; Киевский ВКЗ; Брянський вокзал; Кіеўскі ВКЗ
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 12%|█▏        | 6/50 [00:11<01:19,  1.81s/it]

====== # 16200 ======
Text: фспп ур база данных проверить задолженность по фамилии
Название организации: Лазаревский районный отдел службы судебных приставов; Federal Bailiffs Service; FBS; Судебные приставы; Лазаревский РОСП; Лазаревский Районный Отдел Судебных Приставов Города Сочи Управления Федеральной Службы Судебных Приставов по Краснодарскому Краю; Управление Федеральной службы судебных приставов по Краснодарскому краю Лазаревский районный отдел; Lazarevsky ROSP; ФССП России
GT:   1
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 14%|█▍        | 7/50 [00:12<01:16,  1.77s/it]

====== # 7454 ======
Text: Субару
Название организации: Mazda РОЛЬФ Лахта; Mazda Рольф
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 16%|█▌        | 8/50 [00:14<01:19,  1.89s/it]

====== # 16999 ======
Text: хендай
Название организации: Юг-Авто Hyundai Яблоновский; Yug-Avto Hyundai; Hyundai; Автосалон Hyundai Юг-Авто; Хендай; Хёндай; Юг-Авто Хендэ; Юг-авто; Hyundai Yug-Avto
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 18%|█▊        | 9/50 [00:16<01:17,  1.90s/it]

====== # 13819 ======
Text: где перекусить в выборге недорого
Название организации: Буфет СССР; Bufet SSSR; СССР; Bufet Sssr
GT:   1
content: 5. Ответ дай строго в форм
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 20%|██        | 10/50 [00:18<01:14,  1.86s/it]

====== # 27846 ======
Text: частная массажистка бутово
Название организации: Частная практика; Clinic Chastnaya praktika; Chastnaya praktika; Медицинская клиника Частная практика; Медицинский центр Частная практика; Медицинский центр Частная практика на Варшавской; Klinika Chastnaya praktika
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 22%|██▏       | 11/50 [00:20<01:10,  1.82s/it]

====== # 31026 ======
Text: фастфуд
Название организации: Суши Панда
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 24%|██▍       | 12/50 [00:22<01:07,  1.79s/it]

====== # 1472 ======
Text: евпатория снять
Название организации: Аура-Крым; Aura-Krym
GT:   0
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 26%|██▌       | 13/50 [00:23<01:05,  1.77s/it]

====== # 13592 ======
Text: Наркологии
Название организации: Инстамед; Instamed; Инстамед Внуково; Медицинский цент Инстамед
GT:   0
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 28%|██▊       | 14/50 [00:25<01:02,  1.74s/it]

====== # 12585 ======
Text: оружейник
Название организации: Аквариус; Salon Akvarius; Akvarius; Салон Аквариус
GT:   0
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 30%|███       | 15/50 [00:27<01:04,  1.85s/it]

====== # 30889 ======
Text: завод вторчермет
Название организации: Вторчермет НЛМК Пермь; Uvm; Вторчермет Лнмк Пермь; Вторчермет НЛМК; УВМ; Vtorchermet Lnmk Perm; Увм
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 32%|███▏      | 16/50 [00:29<01:04,  1.89s/it]

====== # 11720 ======
Text: центр технической инвентаризации
Название организации: Поволжское региональное БТИ; Региональное БТИ; Povolzhskoye Regionalnoye Bti; БТИ
GT:   1
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 34%|███▍      | 17/50 [00:31<01:00,  1.84s/it]

====== # 4853 ======
Text: обанкротиться
Название организации: Центр банкротства физических лиц; BFL-Centr; БФЛ центр; Бфл центр
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 36%|███▌      | 18/50 [00:32<00:57,  1.80s/it]

====== # 4001 ======
Text: мебел ный
Название организации: Geniuspark; JeniusPark; Джениуспарк
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 38%|███▊      | 19/50 [00:34<00:55,  1.78s/it]

====== # 25312 ======
Text: рестораны с мишленовскими звездами в москве 2017
Название организации: Дарбази; Darbazi; Ресторан Darbazi; Ресторан Дарбази
GT:   0
content: 5. Ответ в формате JSON строки
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 40%|████      | 20/50 [00:36<00:52,  1.75s/it]

====== # 30913 ======
Text: ближайший продуктовый круглосуточный магазин
Название организации: Вместе; Vmeste
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 42%|████▏     | 21/50 [00:38<00:51,  1.76s/it]

====== # 21318 ======
Text: промышленное производство
Название организации: Агропромышленный парк Казань; Agropromyshlenny park Kazan; Kazan agrosanewat parku; Agropromyshlenny park; Агропромышленный парк; Агропарк Казань; Агропромпарк; Казань
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 44%|████▍     | 22/50 [00:40<00:51,  1.85s/it]

====== # 9700 ======
Text: шенгенская виза в воронеже италия стоимость
Название организации: Первый воронежский визовый центр; ПВЦ
GT:   0
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 46%|████▌     | 23/50 [00:42<00:51,  1.90s/it]

====== # 14614 ======
Text: испанский ресторан цветной бульвар
Название организации: Испанский стыд; Бутербродная Испанский стыд
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 48%|████▊     | 24/50 [00:43<00:48,  1.85s/it]

====== # 17118 ======
Text: ножницы
Название организации: Весёлые ножницы; Veselie nojnitsy
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 50%|█████     | 25/50 [00:49<01:12,  2.89s/it]

====== # 14728 ======
Text: квартиры посуточно в челябинске на карте
Название организации: Лондон; London; Hotel London; Гостиница Лондон; Мини отель Лондон; Мини-отель Лондон; Отель Лондон; Hotel London Chelyabinsk
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 52%|█████▏    | 26/50 [00:54<01:26,  3.59s/it]

====== # 24032 ======
Text: магазин комнатных цветов москва
Название организации: Комнатные Растения; Komnatnye Rasteniya
GT:   0
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 54%|█████▍    | 27/50 [00:56<01:10,  3.07s/it]

====== # 2688 ======
Text: ламизил спрей
Название организации: Здравсити; Zdravcity; Здравсити аптека
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 56%|█████▌    | 28/50 [00:58<00:58,  2.67s/it]

====== # 32522 ======
Text: андреев алексей анатольевич москва озеленение
Название организации: LandCompany
GT:   0
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 58%|█████▊    | 29/50 [00:59<00:49,  2.38s/it]

====== # 23151 ======
Text: ремонт глушителей
Название организации: Феррум; Ferrum
GT:   1
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 60%|██████    | 30/50 [01:01<00:43,  2.18s/it]

====== # 28852 ======
Text: рестораны со звездами мишлен россия
Название организации: Rostic's
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 62%|██████▏   | 31/50 [01:03<00:38,  2.04s/it]

====== # 25280 ======
Text: рыбалка с проживанием в домиках
Название организации: Золотые Караси; Zolotye Karasi; Рыболовная усадьба Золотые караси; Fishing farm Golden carp
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 64%|██████▍   | 32/50 [01:04<00:34,  1.94s/it]

====== # 24560 ======
Text: Фото на документы метро академическая
Название организации: Фото Экспресс СПб; Foto Express SPb
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 66%|██████▌   | 33/50 [01:07<00:34,  2.01s/it]

====== # 3008 ======
Text: Страховой магазин
Название организации: Югория; Yugoriya; YUgoriya
GT:   1
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 68%|██████▊   | 34/50 [01:09<00:31,  1.98s/it]

====== # 3731 ======
Text: стейк в перми где поесть
Название организации: L12
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 70%|███████   | 35/50 [01:10<00:28,  1.90s/it]

====== # 15387 ======
Text: экономический колледж
Название организации: Стоматологический колледж № 1; dentalcollege.ru; Стоматколледж №1
GT:   0
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 72%|███████▏  | 36/50 [01:12<00:25,  1.84s/it]

====== # 25021 ======
Text: запчасти газель
Название организации: Планета Железяка; Planeta Zhelezyaka
GT:   0
content: 5. Ответь только в формате
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 74%|███████▍  | 37/50 [01:14<00:23,  1.80s/it]

====== # 17090 ======
Text: 24 запчасти адреса спб
Название организации: Avtolavka.net; Avtolavka; Avtolavka. Net; Avtolavka.Net; Avtolavka. net
GT:   0
content: 5. Ответ дай строго в форм
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 76%|███████▌  | 38/50 [01:15<00:21,  1.79s/it]

====== # 28289 ======
Text: где в самаре делают документы о стаже работы
Название организации: Медгард; Medguard; Лечебно-диагностический комплекс МедГард; Лечебно-диагностический комплекс Медгард; МедГард; Многопрофильный Лечебно-диагностический комплекс
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 78%|███████▊  | 39/50 [01:17<00:19,  1.77s/it]

====== # 10762 ======
Text: грузинские рестораны москвы
Название организации: Хинкальная; Khinkalnaya; Cafe Khinkalnaya; Кафе Хинкальная; Кафе Хинкальная на Неглинной; Хинкальная на Неглинной
GT:   1
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 80%|████████  | 40/50 [01:19<00:18,  1.86s/it]

====== # 5665 ======
Text: соколов ювелирныи
Название организации: Sokolov; SOKOLOV
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 82%|████████▏ | 41/50 [01:21<00:17,  1.91s/it]

====== # 23096 ======
Text: Автовакзал
Название организации: Автовокзал Барнаул; Avtovokzal; Автовокзал; Avtovokzal goroda Barnaul; Bus terminal Barnaul
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 84%|████████▍ | 42/50 [01:23<00:14,  1.85s/it]

====== # 15276 ======
Text: теле2 е-сим купить
Название организации: t2; Tele2; Т2 Mobile; Теле2; Центр обслуживания абонентов Tele2; T2 Mobile
GT:   1
content: 5. Ответ дай строго в форм
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 86%|████████▌ | 43/50 [01:25<00:12,  1.81s/it]

====== # 17584 ======
Text: шиномонтаж химки ивакино
Название организации: Лукавто; Lukavto; ЛУКАВТО
GT:   0
content: 5. Ответ дай строго в форм
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 88%|████████▊ | 44/50 [01:26<00:10,  1.80s/it]

====== # 3867 ======
Text: кроссфит зал
Название организации: Кроссфит-клуб Союз Спорт; Crossfit-club Soyuz Sport; Crossfit; Лига; МСКФИТ; Мскфит; Союз Спорт; Союз спорт; Спортивный комплекс; Фитнес Лига; Soyuz Sport
GT:   1
content: 5. Ответ дай в формате
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 90%|█████████ | 45/50 [01:28<00:08,  1.77s/it]

====== # 22539 ======
Text: ресторан суши
Название организации: Моремания; Moremania
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 92%|█████████▏| 46/50 [01:30<00:07,  1.75s/it]

====== # 10478 ======
Text: купить 2 комн кв в спб ул благодатная
Название организации: Cartel Lounge; Cartel; SheeBar Lounge; Картель
GT:   0
content: 5. Ответ дай только в формат
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 94%|█████████▍| 47/50 [01:32<00:05,  1.88s/it]

====== # 4027 ======
Text: hyundai
Название организации: Hyundai Favorit Motors Север; Hyundai Favorit Motors North; Hyundai Favorit Motors; FAVORIT MOTORS Hyundai; Автосалон FAVORIT MOTORS Hyundai Север; Автосалон Favorit Motors Hyundai Север — официальный дилер Hyundai; Автосалон Favorit Motors Hyundai — официальный дилер Hyundai; Фаворит Моторс; Car dealership FAVORIT MOTORS Hyundai North — official dealer of Hyundai; Car dealership Favorit Motors Hyundai — official dealer of Hyundai; Сar dealership FAVORIT MOTORS Hyundai North
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

 96%|█████████▌| 48/50 [01:34<00:03,  1.91s/it]

====== # 34525 ======
Text: выставка маникюра в москве 2019
Название организации: Flakon; Flakon. Beauty
GT:   0
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

 98%|█████████▊| 49/50 [01:36<00:01,  1.87s/it]

====== # 20531 ======
Text: бокс секция
Название организации: Фитнес-Арена 3000; Fitness-Arena 3000; Arena 3000; Арена 3000; Территория 3000; Фитнес Арена 3000; Фитнес-арена 3000; Чемпион; Чемпион фитнес-парк; Fitness Arena 3000
GT:   1
content: 5. Ответ всегда в формате JSON
PRED: 0
РЕЗУЛЬТАТ: НЕВЕРНО ❌
----------------------------------------

100%|██████████| 50/50 [01:37<00:00,  1.96s/it]

====== # 34266 ======
Text: ремонт вариатора спб
Название организации: Кореана; Koreana
GT:   0
content: 5. Ответ всегда должен быть в формат
PRED: 0
РЕЗУЛЬТАТ: ВЕРНО ✅
----------------------------------------

In [ ]:
# --- Итоговая метрика ---
accuracy = correct / total if total > 0 else 0.0

print("\n====================")
print(f"Accuracy: {accuracy:.3f}")
print(f"Correct: {correct} / {total}")
print("====================")

====================
Accuracy: 0.460
Correct: 23 / 50
====================

In [ ]:
golden_set

,Text,address,name,normalized_main_rubric_name_ru,permalink,prices_summarized,reviews_summarized,relevance,baseline_pred
19505,недорогие кафе геленджика,"Краснодарский край, Геленджик, Революционная у...",Весёлая Кума; Vesolaya kuma; Весёлая кума; Рес...,Кафе,217958810939,None,Организация «Весёлая Кума» занимается обслужив...,1.0,0
12621,билет надо казахстан москва,"Москва, улица Маршала Василевского, 17",Трансмост-тур; Transmost-tour; Transmost-tur,Железнодорожные билеты,1283162900,None,Организация занимается продажей железнодорожны...,1.0,0
2536,слесарный разметочный инструмент,"Москва, Павловская улица, 27с4",Milwaukee,Строительный инструмент,135317272124,Milwaukee предлагает электро- и бензоинструмен...,Организация занимается продажей и демонстрацие...,1.0,0
11967,главный жд вокзал,"Москва, площадь Киевского Вокзала, 1",Киевский вокзал; Kiyevsky Rail Terminal; Кіеўс...,Железнодорожный вокзал,1095876672,None,Общий обзор отзывов: Киевский вокзал оценивает...,1.0,0
16200,фспп ур база данных проверить задолженность по...,"Краснодарский край, Сочи, жилой район Лазаревс...",Лазаревский районный отдел службы судебных при...,Судебные приставы,1313648395,None,Организация занимается исполнением судебных ре...,1.0,0
16999,хендай,"Республика Адыгея (Адыгея), аул Тахтамукай, Кр...",Юг-Авто Hyundai Яблоновский; Yug-Avto Hyundai;...,Автосалон,1177113559,Автосалон и автотехцентр «Юг-Авто Hyundai Ябло...,Организация занимается продажей автомобилей с ...,1.0,0
13819,где перекусить в выборге недорого,"Ленинградская область, Выборг, улица Гагарина, 4",Буфет СССР; Bufet SSSR; СССР; Bufet Sssr,Кафе,97907735549,None,Организация «Буфет СССР» предлагает блюда в ст...,1.0,0
31026,фастфуд,"Новосибирск, Кубовая улица, 94/1",Суши Панда,Быстрое питание,124847088093,«Суши Панда» предлагает широкий ассортимент су...,Организация занимается приготовлением и достав...,1.0,0
30889,завод вторчермет,"Пермь, Соликамская улица, 283",Вторчермет НЛМК Пермь; Uvm; Вторчермет Лнмк Пе...,Приём и скупка вторсырья,1467650517,None,Организация занимается приёмом и скупкой вторс...,1.0,0
11720,центр технической инвентаризации,"Самара, улица 22-го Партсъезда, 45",Поволжское региональное БТИ; Региональное БТИ;...,БТИ,150178058866,None,Организация занимается предоставлением услуг Б...,1.0,0
4853,обанкротиться,"Москва, Большой Дровяной переулок, 21/12",Центр банкротства физических лиц; BFL-Centr; Б...,Юридические услуги,21911129159,None,Организация занимается оказанием юридических у...,1.0,0
4001,мебел ный,"Санкт-Петербург, Варшавская улица, 3к1",Geniuspark; JeniusPark; Джениуспарк,Магазин мебели,1492739999,None,"Организация занимается продажей мебели, в част...",1.0,0
30913,ближайший продуктовый круглосуточный магазин,"Санкт-Петербург, Ковенский переулок, 1",Вместе; Vmeste,Супермаркет,62478282342,Супермаркет «Вместе» предлагает широкий ассорт...,"Организация «Вместе» — это супермаркет, которы...",1.0,0
14614,испанский ресторан цветной бульвар,"Москва, Кривоколенный переулок, 10, стр. 5",Испанский стыд; Бутербродная Испанский стыд,"Бар , паб",209124813099,None,Организация «Испанский стыд» — это бар с акцен...,1.0,0
2688,ламизил спрей,"Москва, Скобелевская улица, 20",Здравсити; Zdravcity; Здравсити аптека,Аптека,223915879647,"Здравсити — аптека, предлагающая широкий спект...",Организация занимается продажей лекарственных ...,1.0,0
23151,ремонт глушителей,"Московская область, Наро-Фоминский городской о...",Феррум; Ferrum,Шиномонтаж,81325860221,Организация «Феррум» предоставляет услуги шино...,"Организация занимается шиномонтажом, работает ...",1.0,0
25280,рыбалка с проживанием в домиках,"Московская область, городской округ Щёлково, д...",Золотые Караси; Zolotye Karasi; Рыболовная уса...,"База , дом отдыха",123298530111,Дом отдыха «Золотые Караси» предлагает аренду ...,Организация «Золотые Караси» предоставляет усл...,1.0,0
24560,Фото на документы метро академическая,"Санкт-Петербург, проспект Культуры, 20",Фото Экспресс СПб; Foto Express SPb,Фотоуслуги,120148011516,Фото Экспресс СПб предлагает фотоуслуги и услу...,Организация занимается предоставлением фотоусл...,1.0,0
3008,Страховой магазин,"Ивановская область, Кинешма, площадь Революции...",Югория; Yugoriya; YUgoriya,Страховая компания,94672332735,Страховая компания «Югория» предлагает широкий...,Организация занимается страхованием автомобиле...,1.0,0
3731,стейк в перми где поесть,"Пермь, Ласьвинская улица, 12",L12,Ресторан,1796713673,None,Организация занимается ресторанным обслуживани...,1.0,0

## Добавляем Chain-of-Thoghts (разрешаем модели размышлять)

In [ ]:
print(f"🧪 Тестируем Smart Baseline на {len(golden_set)} сложных примерах...")

# 1. Улучшенная функция парсинга (умеет доставать JSON из текста с рассуждениями)
def parse_cot_response(content: str) -> dict:
    """
    Ищет JSON-объект в ответе модели.
    Возвращает словарь с reasoning и relevant или дефолтный Fail.
    """
    try:
        # Убираем маркеры кода, если есть
        content = re.sub(r"```json", "", content)
        content = re.sub(r"```", "", content)

        # Ищем фигурные скобки
        matches = re.findall(r"\{.*?\}", content, flags=re.DOTALL)
        if matches:
            # Берем последний найденный JSON (часто модель сначала пишет пример, потом ответ)
            last_match = matches[-1]
            data = json.loads(last_match)
            return data
    except Exception as e:
        pass

    return {"reasoning": "Parse Error", "relevant": 0}

# 2. Промпт с Chain-of-Thought (CoT)
def predict_with_cot(row, model, tokenizer):
    prompt = f"""
Ты — аналитик данных. Твоя задача — проверить, соответствует ли найденная организация запросу пользователя.

Запрос пользователя: "{row['Text']}"
Кандидат (Организация):
- Название: "{row['name']}"
- Адрес: "{row['address']}"
- Категория: "{row['normalized_main_rubric_name_ru']}"

ИНСТРУКЦИЯ:
1. Сначала напиши рассуждение (reasoning). Проанализируй совпадение по смыслу, адресу и категории. Обрати внимание на детали (например, "опт" vs "розница", "ремонт" vs "продажа").
2. Сделай итоговый вывод (verdict).
3. Верни ответ СТРОГО в формате JSON.

Формат ответа:
{{
    "reasoning": "Твой пошаговый анализ здесь...",
    "relevant": 1 (если подходит) или 0 (если нет)
}}

Не пиши ничего лишнего за пределами JSON.
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=300,  # Увеличили токенов, так как нужно reasoning
            temperature=0.0,     # Оставляем 0 для стабильности, но рассуждение добавит гибкости
            do_sample=False
        )

    generated_text = tokenizer.decode(output[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    return parse_cot_response(generated_text), generated_text

🧪 Тестируем Smart Baseline на 20 сложных примерах...

In [ ]:
# 3. Запуск эксперимента
results_cot = []
fixed_count = 0

print("Запуск CoT (думаем перед ответом)...")

for idx, row in tqdm(golden_set.iterrows(), total=len(golden_set)):
    prediction_data, raw_text = predict_with_cot(row, model, tokenizer)

    pred_val = float(prediction_data.get("relevant", 0))
    true_val = float(row["relevance"])

    is_correct = (pred_val == true_val)
    if is_correct:
        fixed_count += 1

    results_cot.append({
        "query": row["Text"],
        "org_name": row["name"],
        "true_relevance": true_val,
        "pred_relevance": pred_val,
        "reasoning": prediction_data.get("reasoning", ""),
        "is_fixed": is_correct
    })

# 4. Анализ результатов
print(f"Итоги Smart Baseline (CoT):")
print(f"Было ошибок: {len(golden_set)}")
print(f"Исправлено благодаря CoT: {fixed_count}")
print(f"Осталось сложных ошибок: {len(golden_set) - fixed_count}")
print(f"Прирост точности на сложных примерах: {fixed_count / len(golden_set):.2%}")

# Показываем примеры исправлений
df_res = pd.DataFrame(results_cot)
if fixed_count > 0:
    print("Пример успешного исправления:")
    row_fixed = df_res[df_res["is_fixed"] == True].iloc[0]
    print(f"Запрос: {row_fixed['query']}")
    print(f"Орг: {row_fixed['org_name']}")
    print(f"Reasoning: {row_fixed['reasoning']}")
else:
    print("CoT не помог. Значит, проблема действительно в нехватке информации!")

🚀 Запуск CoT (думаем перед ответом)...

100%|██████████| 20/20 [14:27<00:00, 43.40s/it]

📊 Итоги Smart Baseline (CoT):
Было ошибок: 20
Исправлено благодаря CoT: 12
Осталось сложных ошибок: 8
Прирост точности на сложных примерах: 60.00%

✅ Пример успешного исправления:
Запрос: недорогие кафе геленджика
Орг: Весёлая Кума; Vesolaya kuma; Весёлая кума; Ресторан Весёлая Кума
Reasoning: По запросу 'недорогие кафе геленджика' ищется организация, которая относится к категории 'кафе' и находится в городе Геленджик. Найденная организация 'Весёлая Кума' соответствует категории 'Кафе' и находится в Геленджике. Однако, информация о том, что это недорогое место, отсутствует. Кроме того, название организации может быть не совсем точным, так как в запросе нет слова 'весёлая', но это может быть просто частью названия. Адрес также соответствует городу Геленджик.

## Web-search

In [ ]:
!pip install tavily-python trafilatura

Collecting tavily-python
  Downloading tavily_python-0.7.19-py3-none-any.whl.metadata (9.0 kB)
Collecting trafilatura
  Downloading trafilatura-2.0.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from tavily-python) (2.32.4)
Requirement already satisfied: tiktoken>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tavily-python) (0.12.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from tavily-python) (0.28.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from trafilatura) (2026.1.4)
Requirement already satisfied: charset_normalizer>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from trafilatura) (3.4.4)
Collecting courlan>=1.3.2 (from trafilatura)
  Downloading courlan-1.3.2-py3-none-any.whl.metadata (17 kB)
Collecting htmldate>=1.9.2 (from trafilatura)
  Downloading htmldate-1.9.4-py3-none-any.whl.metadata (10 kB)
Collecting justext>=3.0.1 (from trafilatura)
  Downloading justext-3.0.2-py2.py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: lxml>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from trafilatura) (6.0.2)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from trafilatura) (2.5.0)
Requirement already satisfied: babel>=2.16.0 in /usr/local/lib/python3.12/dist-packages (from courlan>=1.3.2->trafilatura) (2.17.0)
Collecting tld>=0.13 (from courlan>=1.3.2->trafilatura)
  Downloading tld-0.13.1-py2.py3-none-any.whl.metadata (10 kB)
Collecting dateparser>=1.1.2 (from htmldate>=1.9.2->trafilatura)
  Downloading dateparser-1.2.2-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: python-dateutil>=2.9.0.post0 in /usr/local/lib/python3.12/dist-packages (from htmldate>=1.9.2->trafilatura) (2.9.0.post0)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken>=0.5.1->tavily-python) (2025.11.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->tavily-python) (3.11)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx->tavily-python) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->tavily-python) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->tavily-python) (0.16.0)
Requirement already satisfied: pytz>=2024.2 in /usr/local/lib/python3.12/dist-packages (from dateparser>=1.1.2->htmldate>=1.9.2->trafilatura) (2025.2)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser>=1.1.2->htmldate>=1.9.2->trafilatura) (5.3.1)
Collecting lxml_html_clean (from lxml[html_clean]>=4.4.2->justext>=3.0.1->trafilatura)
  Downloading lxml_html_clean-0.4.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.9.0.post0->htmldate>=1.9.2->trafilatura) (1.17.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx->tavily-python) (4.15.0)
Downloading tavily_python-0.7.19-py3-none-any.whl (18 kB)
Downloading trafilatura-2.0.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.6/132.6 kB 17.5 MB/s eta 0:00:00
Downloading courlan-1.3.2-py3-none-any.whl (33 kB)
Downloading htmldate-1.9.4-py3-none-any.whl (31 kB)
Downloading justext-3.0.2-py2.py3-none-any.whl (837 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 837.9/837.9 kB 59.5 MB/s eta 0:00:00
Downloading dateparser-1.2.2-py3-none-any.whl (315 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.5/315.5 kB 22.1 MB/s eta 0:00:00
Downloading tld-0.13.1-py2.py3-none-any.whl (274 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.7/274.7 kB 35.5 MB/s eta 0:00:00
Downloading lxml_html_clean-0.4.3-py3-none-any.whl (14 kB)
Installing collected packages: tld, lxml_html_clean, dateparser, courlan, tavily-python, justext, htmldate, trafilatura
Successfully installed courlan-1.3.2 dateparser-1.2.2 htmldate-1.9.4 justext-3.0.2 lxml_html_clean-0.4.3 tavily-python-0.7.19 tld-0.13.1 trafilatura-2.0.0

In [ ]:
import trafilatura
from tavily import TavilyClient
from google.colab import userdata


print("🌐 Подключаем Web-search...")

TAVILY_API_KEY = userdata.get('Tavily')
tavily_client = TavilyClient(api_key=TAVILY_API_KEY)

def clean_search_query(row):
    # 1. Берем только первое название (до точки с запятой)
    name = row['name'].split(';')[0].strip()

    # 2. Пытаемся вытащить город из адреса
    # Обычно адрес это "Город, улица, дом"
    address_parts = row['address'].split(',')
    city = address_parts[0].strip()

    # Если первое слово "Россия", берем второе (это город)
    if "Россия" in city and len(address_parts) > 1:
        city = address_parts[1].strip()

    # Формируем человеческий запрос
    return f"{name} {city} официальный сайт услуги"

def search_tavily_safe(query, max_results=2):
    try:
        # search_depth="advanced" дает более качественные результаты
        response = tavily_client.search(query, search_depth="advanced", max_results=max_results)
        # Tavily возвращает сразу список словарей [{'url': ..., 'content': ...}]
        # Мы пока возьмем только URL, чтобы сохранить логику пайплайна (свой скрапер)
        # Но вообще Tavily уже возвращает распаршенный контент!
        return [r['url'] for r in response['results']]
    except Exception as e:
        print(f"Tavily Error: {e}")
        return []

# 4. Скрапер (Trafilatura)
def smart_scrape(url):
    try:
        downloaded = trafilatura.fetch_url(url)
        if downloaded is None:
            return None
        text = trafilatura.extract(downloaded, include_comments=False, include_tables=False)
        return text
    except Exception:
        return None

🌐 Подключаем Web-search...
Введите ваш Tavily API Key: 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

In [ ]:
# 4. Тест "Глаз" на сложных примерах
print(f"🕵️ Проверяем, поможет ли поиск для {len(golden_set)} сложных случаев...")

web_results = []

# Берем первые 5 примеров из Golden Set для теста (чтобы не ждать долго)
# В реальном запуске уберем .head()
for idx, row in tqdm(golden_set.head(5).iterrows(), total=5):

    # Формируем поисковый запрос: Название + Город + Адрес
    # Это важно! Просто названия часто недостаточно.
    human_query = clean_search_query(row)

    # Ищем
    urls = search_tavily_safe(human_query)

    found_text = "Ничего не найдено"
    used_url = "None"

    # 2. Читаем первый доступный сайт
    for url in urls:
        text = smart_scrape(url)
        if text and len(text) > 100: # Если текста достаточно много
            found_text = text[:1000] + "..." # Берем первые 1000 символов для превью
            used_url = url
            break

        time.sleep(1)

    web_results.append({
        "query": row['Text'],
        "org_name": row['name'],
        "search_query": human_query,
        "found_url": used_url,
        "scraped_content": found_text
    })
    time.sleep(0.5)

# 5. Вывод результатов
df_web = pd.DataFrame(web_results)

# Настройка отображения, чтобы текст не обрезался
pd.set_option('display.max_colwidth', 150)
display(df_web)

🕵️ Проверяем, поможет ли поиск для 20 сложных случаев...

  0%|          | 0/5 [00:00<?, ?it/s]ERROR:trafilatura.downloads:not a 200 response: 403 for URL https://www.tripadvisor.ru/Restaurant_Review-g298514-d8654562-Reviews-Vesyolaya_Kuma-Gelendzhik_Gelendzhiksky_District_Krasnodar_Krai_Southern_District.html
 80%|████████  | 4/5 [00:29<00:07,  7.07s/it]ERROR:trafilatura.downloads:not a 200 response: 403 for URL https://gosuslugi41.ru/pgu/offices/info.htm?id=12297@egOffice
ERROR:trafilatura.downloads:download error: https://pgu.krasnodar.ru/ HTTPSConnectionPool(host='pgu.krasnodar.ru', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9985dbf680>, 'Connection to pgu.krasnodar.ru timed out. (connect timeout=30)'))
100%|██████████| 5/5 [01:09<00:00, 13.81s/it]

,query,org_name,search_query,found_url,scraped_content
0,недорогие кафе геленджика,Весёлая Кума; Vesolaya kuma; Весёлая кума; Ресторан Весёлая Кума,Весёлая Кума Краснодарский край официальный сайт услуги,https://kuma.pirnnov.ru/,"Ресторан ""Веселая Кума""\nРусская кухня\nКубанская кухня так близка русскому человеку. Драники с беконом, вареники, борщ с пампушками и фирменные н..."
1,билет надо казахстан москва,Трансмост-тур; Transmost-tour; Transmost-tur,Трансмост-тур Москва официальный сайт услуги,https://transmost-tour.ru/tourizm/,Туристическая компания «Трансмост-тур» является опытным агентством с обширной сетью офисов по Москве. Профессионализм и опыт наших сотрудников поз...
2,слесарный разметочный инструмент,Milwaukee,Milwaukee Москва официальный сайт услуги,https://milwrussia.ru/,"Для смены лезвия, требуется доработка карандаша. При извлечение лезвия удерживающий штифт ломается, либо сгибается, приходится нарезать резьбу, ст..."
3,главный жд вокзал,Киевский вокзал; Kiyevsky Rail Terminal; Кіеўскі вакзал; Kiewer Bahnhof; Gare de Kiev; Kiev Garı; Київський вокзал; Kievsky Rail Terminal; Брянски...,Киевский вокзал Москва официальный сайт услуги,https://www.msk-guide.ru/oficialnyj-sajt-i-telefon-kievskogo-vokzala.htm,Официальный сайт и телефон Киевского вокзала\nТелефон\nМногоканальный телефон единой справочной ОАО РЖД 8 (800) 775-00-00 (бесплатно с территории ...
4,фспп ур база данных проверить задолженность по фамилии,Лазаревский районный отдел службы судебных приставов; Federal Bailiffs Service; FBS; Судебные приставы; Лазаревский РОСП; Лазаревский Районный Отд...,Лазаревский районный отдел службы судебных приставов Краснодарский край официальный сайт услуги,None,Ничего не найдено